-- V9__add_pagamento_fields.sql
ALTER TABLE vendas ADD COLUMN IF NOT EXISTS forma_pagamento VARCHAR(20);
ALTER TABLE vendas ADD COLUMN IF NOT EXISTS numero_parcelas INTEGER DEFAULT 1;
ALTER TABLE vendas ADD COLUMN IF NOT EXISTS valor_entrada DECIMAL(10,2) DEFAULT 0;
ALTER TABLE vendas ADD COLUMN IF NOT EXISTS valor_parcela DECIMAL(10,2) DEFAULT 0;
ALTER TABLE vendas ADD COLUMN IF NOT EXISTS bandeira_cartao VARCHAR(20);
ALTER TABLE vendas ADD COLUMN IF NOT EXISTS ultimos_digitos VARCHAR(4);